name: renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: info
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: [master]
    paths:
      - .github/renovate.json
      - .github/renovate/**.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'info' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_FORK_PROCESSING: enabled
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"

jobs:
  renovate:
    name: scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TERRAFORM_GITHUB_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_GITHUB_APP_PEM }}

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.6
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: .github/renovate.json
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
